export const POSTS = [
	{
		_id: "1",
		text: "Let's build a fullstack WhatsApp clone with NEXT.JS 14 😍",
		img: "https://github.com/burakorkmez/twitter-clone/blob/master/frontend/public/posts/post1.png?raw=true",
		user: {
			username: "johndoe",
			profileImg: "https://github.com/burakorkmez/twitter-clone/blob/master/frontend/public/avatars/girl1.png?raw=true",
			fullName: "John Doe",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "janedoe",
					profileImg: "/avatars/girl1.png",
					fullName: "Jane Doe",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "2",
		text: "How you guys doing? 😊",
		user: {
			username: "johndoe",
			profileImg: "https://github.com/burakorkmez/twitter-clone/blob/master/frontend/public/avatars/girl1.png?raw=true",
			fullName: "John Doe",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "janedoe",
					profileImg: "https://github.com/burakorkmez/twitter-clone/blob/master/frontend/public/avatars/girl1.png?raw=true",
					fullName: "Jane Doe",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "3",
		text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
		img: "https://github.com/burakorkmez/twitter-clone/blob/master/frontend/public/posts/post2.png?raw=true",
		user: {
			username: "johndoe",
			profileImg: "https://github.com/burakorkmez/twitter-clone/blob/master/frontend/public/avatars/girl1.png?raw=true",
			fullName: "John Doe",
		},
		comments: [],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894", "6658s895", "6658s896"],
	},
	{
		_id: "4",
		text: "I'm learning GO this week. Any tips? 🤔",
		img: "https://github.com/burakorkmez/twitter-clone/blob/master/frontend/public/posts/post3.png?raw=true",
		user: {
			username: "johndoe",
			profileImg: "https://github.com/burakorkmez/twitter-clone/blob/master/frontend/public/avatars/girl1.png?raw=true",
			fullName: "John Doe",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "janedoe",
					profileImg: "https://github.com/burakorkmez/twitter-clone/blob/master/frontend/public/avatars/girl1.png?raw=true",
					fullName: "Jane Doe",
				},
			},
		],
		likes: [
			"6658s891",
			"6658s892",
			"6658s893",
			"6658s894",
			"6658s895",
			"6658s896",
			"6658s897",
			"6658s898",
			"6658s899",
		],
	},
];

export const user = [
	{
		_id: "1",
		fullName: "John Doe",
		username: "johndoe",
		profileImg: "https://github.com/burakorkmez/twitter-clone/blob/master/frontend/public/avatars/boy1.png?raw=true",
	},
	{
		_id: "2",
		fullName: "Jane Doe",
		username: "janedoe",
		profileImg: "https://github.com/burakorkmez/twitter-clone/blob/master/frontend/public/avatars/girl1.png?raw=true",
	},
	{
		_id: "3",
		fullName: "Bob Doe",
		username: "bobdoe",
		profileImg: "https://github.com/burakorkmez/twitter-clone/blob/master/frontend/public/avatars/boy1.png?raw=true",
	},
	{
		_id: "4",
		fullName: "Daisy Doe",
		username: "daisydoe",
		profileImg: "https://github.com/burakorkmez/twitter-clone/blob/master/frontend/public/avatars/girl2.png?raw=true",
	},
];